### ISSUE TITLE
unversioned redirects - robots directive no-index - remove?

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/docs#190]
#### Summary:

as written, the unversioned redirects put in a "robots noindex" in the head.
is this the right thing to do?

#### Description:
Describe the issue as clearly as possible.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.18.0

**Comment by jgabry** [comment]
No idea! Any ideas who might know?

**Comment by bob-carpenter** [comment]
As much as we'd like the top-level page to be indexed because that's where we'd like to send people, there's no content there to index other than the redirect.  So I'm not sure what would happen if we did allow them to be indexed.  I don't see how it could hurt because it's where we'd like people to land.

**Comment by WardBrian** [comment]
No longer relevant with the current repo organization
