### ISSUE TITLE
return codes defined and documented

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/docs#228]
#### Summary:

Return codes for the executable for compiled Stan programs are not defined.  Define them and add them to the CmdStan documentation.

#### Description

Return code 0 should indicate that everything returned normally and that all expected output exists.  It does *not* need to indicate that the resulting sample is reliable.

#### Current Version:
v2.19.1

**Comment by mortonjt** [comment]
Is there a document for fleshing out these codes?  For instance, I ran into a ret code of `-11`; it wasn't immediately intuitive what that meant, but it turned out that it was an index out of bounds error (I had use zero-indexing instead of 1-based).

**Comment by mitzimorris** [comment]
the Stan services layer return codes are as described above.   however, runtime errors will trigger various return codes that are platform and interface specific.  regarding an index out of bounds error, that sounds like a Python interface problem.
filed https://github.com/stan-dev/cmdstanpy/issues/357

**Comment by mitzimorris** [comment]
@mortonjt - could you provide details on what you did to get the ret code '-11'?   trying to improve error handling in CmdStanPy - https://github.com/stan-dev/cmdstanpy/tree/feature/357-retcode-msg - examples for unit and functional tests would be most useful.

**Comment by mortonjt** [comment]
Hi @mitzimorris not a problem.

To keep it brief, I had initialized the following CmdStanpy model
```python
    sm = CmdStanModel(stan_file=code)
    dat = {
        'N' : len(counts),
        'C' : int(max(case_ids) + 1),
        'depth' : list(map(int, np.log(depth))),
        'y' : list(map(int, counts.astype(np.int64))),
        'cc_bool' : list(map(int, case_member)),
        'cc_ids' : list(map(int, case_ids))
    }
```
The corresponding stan file can be found [here](https://github.com/mortonjt/q2-differential/blob/c5e5d495e3843d71566ad8cf3374eacf2144a209/q2_differential/assets/nb_case_control.stan).

The major error here is that `cc_ids` is a numpy array of ints, which are zero-based.  This is a problem with the Stan code, since it is using one-based indexing. The fix can be easily done on the python side by forcing `cc_ids` strictly greater than or equal to one via `'cc_ids' : list(map(int, case_ids + 1))`

The full pull request with this code can be found here : https://github.com/mortonjt/q2-differential/pull/4

**Comment by mitzimorris** [comment]
@mortonjt - the generated C++ code should have bounds checks so this doesn't happen.  filed bug report on the Stanc3 compiler.  for the record, what version of CmdStan are you running?

**Comment by mortonjt** [comment]
This is the latest version of Cmdstanpy==0.9.68 with the latest install of
Cmdstan (just installed last week, so it should be 2.26.1)

**Comment by mitzimorris** [comment]
return codes, verison tldr:

 return code 0: program completed successfully.

 negative return codes - program was terminated unexpectedly - e.g. segfault or memory access or OOM.

 positive return codes in set {64, 65, 66, 70, 78} indicate problems encountered; informative error messages will be written to stderr.

on some platforms, negative return codes - i.e. signed ints, are interpreted as unsigned short ints, resulting in return codes greater than 127 (max short signed int) e.g. -6 is reported as 134 due to wrong interpretation of the sign bit.

**Comment by mitzimorris** [comment]
added section to users manual as well as appendix.
https://github.com/stan-dev/docs/pull/344
