### ISSUE TITLE
HMM functions description 

### ISSUE THREAD

**Issue by micmicqb** [stan-dev/docs#265]
#### Summary:
Minor inaccuracies in the description of the newly introduced HMM functions `hmm_latent_rng` and `hmm_hidden_state_prob`.

#### Description:
The descriptions for `hmm_latent_rng` and `hmm_hidden_state_prob` (Functions Reference docs) read that these functions can only be used in the transformed data block; it should probably be the transformed parameters block, since they both depend on other parameters \phi.

The description for `hmm_hidden_state_prob` (Functions Reference docs) reads: "The i^{th} column is a simplex of probabilities for the n^{th} variable." This should probably be "The n^{th} column is a simplex of probabilities for the n^{th} variable.

#### Additional Information:
Thank you for the great work you're doing, thorough documentation is vital for such a project.

#### Current Version:
v2.24

**Comment by bbbales2** [comment]
Thanks for the issue! Apologies for the slow response

> This should probably be "The n^{th} column is a simplex of probabilities for the n^{th} variable.

Good catch! Just put in a pull for that (https://github.com/stan-dev/docs/pull/281).

> it should probably be the transformed parameters block, since they both depend on other parameters \phi

`transformed data` is correct here. I agree it would be a bit unusual to do either of these in transformed data but it's possible if you passed in a \phi that was data or something.

The reason that the `hmm_latent_rng` function can't be used in `transformed parameters` is it has a random number generator (and you can't use random number generators in the likelihood calculation).

The way `hmm_hidden_state_prob` is calculated it doesn't have gradients (and work with autodiff), and so that is why it is excluded.
