### ISSUE TITLE
There's always three lines for every function

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/docs#276]
#### Summary:

This line renders:
```
`real` **`normal_lpdf`**`(reals y | reals mu, reals sigma)`<br>\newline
```

And that's great.

Do these two lines do anything? How do I know I've done them right? Can I delete them?

```
<!-- real; normal_lpdf; (reals y | reals mu, reals sigma); -->
\index{{\tt \bfseries normal\_lpdf }!{\tt (reals y \textbar\ reals mu, reals sigma): real}|hyperpage}
```

#### Current Version:
v2.24.0

**Comment by rok-cesnovar** [comment]
I believe at least the HTML comment (the first of the two lines) is used to parsing the stan-functions.txt which is consumed by emacs stan-mode https://github.com/stan-dev/docs/pull/180 and I believe also studio https://github.com/stan-dev/stan/issues/2740

I am not sure about the second line though.

**Comment by bbbales2** [comment]
Ooops, I need to add the html ones back to the ode functions then

**Comment by mitzimorris** [comment]
> Do these two lines do anything? How do I know I've done them right? Can I delete them?
> 
> > 
> > \index{{\tt \bfseries normal\_lpdf }!{\tt (reals y \textbar\ reals mu, reals sigma): real}|hyperpage}
> > 

hi @bbbales2  (can I call you b3n?  b3n2?). these are great questions which need to be documented somewhere - like a wiki page on "all the hacks that go into the docset" -

line 1 is used by script https://github.com/stan-dev/docs/blob/master/extract_function_sigs.py
and this script is used by the folks at RStudio to produce a listing of all Stan math functions available to the user.

line 2 is used by Latex so that the pdf version of the docs has an index.

they are both entirely very necessary.

**Comment by mitzimorris** [comment]
(maybe you know this) - the hack here is that when rendering pdfs via Latex, html directives are ignored, and when rendering html pages via bookdown, latex directives are ignored.  so the Rmd files are cluttered up w/ crap.

when I converted the latex version of the functions ref manual to Rmd, I somehow generated the HTML comments from the Latex index directives via Python scripts.  I think I could do something similar again to get the _lupmf entries.

**Comment by bbbales2** [comment]
Oooo, alright, makes sense. I did not know this.
