### ISSUE TITLE
next manual, 2.20++

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/docs#36]
#### Summary:
This is the place to record typos and brainos or suggestions for the Stan manuals:  User's Guide, Reference Manual, Functions Reference.  Please report broken links, incorrect code or math as well as questions and corrections to discussion and modeling advice.

#### Current Version:
v2.19.0

**Comment by avehtari** [comment]
In section **Normal-Id Generalised Linear Model (Linear Regression)**
`normal_id_glm_lpmf` should be `normal_id_glm_lpdf`

**Comment by jaehyunjoo** [comment]
Just reporting minor things. 

**Stan User's Guide:**
In section 9.2 Soft  K-Means, need to remove a redundant close paren after soft_z[n]
  // likelihood
  for (n in 1:N)
    target += log_sum_exp(soft_z[n])**)**;

**Stan Language Functions Reference:**
In section 15.1 Normal Distribution, may need a close brace? \pitemTwo{y}
std_normal(\pitemTwo{y) and std_normal_lpdf( y | \pitemTwo{y)

**Comment by bob-carpenter** [comment]
Thanks, @jaehyunjoo.  We'll get those fixed.

**Comment by bertcarnell** [comment]
https://github.com/stan-dev/docs/blob/90cb5fd93afae84e35638da0e9f717c6cc128f03/docs/2_19/functions-reference/multivariate-normal-distribution-precision-parameterization.html#L572

https://github.com/stan-dev/docs/blob/90cb5fd93afae84e35638da0e9f717c6cc128f03/docs/2_19/functions-reference/multivariate-normal-distribution-precision-parameterization.html#L573

I think that the above section should be changed from 
`MultiNormalPrecision(y|mu, Omega) = MultiNormal(y|mu, Sigma^-1)` 
to
`MultiNormalPrecision(y|mu, Omega) = MultiNormal(y|mu, Omega^-1)`

**Comment by mitzimorris** [comment]
@bertcarnell - good catch, many thanks!

**Comment by enbrown** [comment]
This line in the Custom Probability Functions chapter of the User Manual doesn't show correctly in the HTML output

https://github.com/stan-dev/docs/blob/90cb5fd93afae84e35638da0e9f717c6cc128f03/src/stan-users-guide/custom-probability.Rmd#L118

Additionally, to have a more consistent format in the LaTeX PDF output, it's possible that the use of `\mbox{binormal\_cdf}` would be better replaced by `\mathtt{binormal\_cdf}` so that the font of this Stan function name is in a monospaced font similar to the monospaced font used in the verbatim Stan code sections.

**Comment by enbrown** [comment]
These 4 equations don't render correctly in the LaTeX PDF version of the User Guide and all show up on the same line without linebreaks between the 4 equations

https://github.com/stan-dev/docs/blob/90cb5fd93afae84e35638da0e9f717c6cc128f03/src/stan-users-guide/latent-discrete.Rmd#L42-L50

This code works in LaTeX but I'm not sure how a LaTeX `align` environment outside of math mode would be processed into HTML by pandoc:
```
\begin{align*}
e   &\sim  \mathsf{Exponential}(r_e) \\
l   &\sim  \mathsf{Exponential}(r_l) \\
s   &\sim  \mathsf{Uniform}(1, T) \\
D_t &\sim  \mathsf{Poisson}(t < s \ ? \ e \ : \ l)
\end{align*}
```

If the `align` LaTeX environment is able to be used, then there are many places throughout the User Guide that could benefit. For example, a little later in the same chapter, the code

https://github.com/stan-dev/docs/blob/90cb5fd93afae84e35638da0e9f717c6cc128f03/src/stan-users-guide/latent-discrete.Rmd#L79-L87

produces an unreadably-long line in the PDF output because its all on one line. Replacing it with 
```
\begin{align*}
p(e,l,s,D)
 &=  p(e) \, p(l) \, p(s) \, p(D | s, e, l) \\
 &=
\mathsf{Exponential}(e|r_e) \ \mathsf{Exponential}(l|r_l) \
\mathsf{Uniform}(s|1, T) \\
 &\qquad \prod_{t=1}^T \mathsf{Poisson}(D_t | t < s \ ? \ e \ : \ l),
\end{align*}
```
would help immensely with readability.

**Comment by enbrown** [comment]
There are scattered lines that show up in both the HTML and PDF outputs as cryptic references to something like `id:foo-stuff.figure`. One example is

https://github.com/stan-dev/docs/blob/90cb5fd93afae84e35638da0e9f717c6cc128f03/src/stan-users-guide/latent-discrete.Rmd#L175

**Comment by mitzimorris** [comment]
@enbrown - many thanks for all of the above.  will investigate and try to address.

**Comment by enbrown** [comment]
Here's another table that's present in the LaTeX PDF output that seems to be missing from the HTML files

https://github.com/stan-dev/docs/blob/90cb5fd93afae84e35638da0e9f717c6cc128f03/src/stan-users-guide/latent-discrete.Rmd#L534-L556

**Comment by enbrown** [comment]
Here are some small typos in the `latent-discrete.Rmd` file:

`doct@rs` should be `doctors` in:
https://github.com/stan-dev/docs/blob/90cb5fd93afae84e35638da0e9f717c6cc128f03/src/stan-users-guide/latent-discrete.Rmd#L897

In a few places the LaTeX nonbreaking space `~` is used rather than the Markdown `\ ` form. So in one, `Equation~(2.7)` should be `Equation\ (2.7)`:
https://github.com/stan-dev/docs/blob/90cb5fd93afae84e35638da0e9f717c6cc128f03/src/stan-users-guide/latent-discrete.Rmd#L577
https://github.com/stan-dev/docs/blob/90cb5fd93afae84e35638da0e9f717c6cc128f03/src/stan-users-guide/latent-discrete.Rmd#L788
https://github.com/stan-dev/docs/blob/90cb5fd93afae84e35638da0e9f717c6cc128f03/src/stan-users-guide/latent-discrete.Rmd#L1002
https://github.com/stan-dev/docs/blob/90cb5fd93afae84e35638da0e9f717c6cc128f03/src/stan-users-guide/latent-discrete.Rmd#L1064
The two figures in section 7.2 seem to result in broken links on the HTML website (possibly due to them being PDF images):
https://github.com/stan-dev/docs/blob/90cb5fd93afae84e35638da0e9f717c6cc128f03/src/stan-users-guide/latent-discrete.Rmd#L277-L279
https://github.com/stan-dev/docs/blob/90cb5fd93afae84e35638da0e9f717c6cc128f03/src/stan-users-guide/latent-discrete.Rmd#L284-L286

**Comment by bob-carpenter** [comment]
@enbrown  Thanks so much for all the careful comments on doc.

Rather than \mbox{foo\_cdf}, we should be using `\textrm{foo\_cdf}`.  Not a big deal.

>  it's possible that the use of \mbox{binormal\_cdf} would be better replaced by \mathtt{binormal\_cdf}

I'm OK with this, but it would be a huge change throughout the doc. 

**WARNING**:  For words, we need to use `\texttt{binormal\_cdf}` rather than the `mathtt` version.  Also, we should be using `\textrm` rather than `\mbox` as it scales size properly.

**Comment by enbrown** [comment]
> I'm OK with this, but it would be a huge change throughout the doc.

Yup, its massive. I've forked the repository, made a ton of changes, and I hope created a pull request correctly. There were random typos, tables and pictures that were missing from the HTML version, text that was missing from the HTML version (but present in the LaTeX version), and fixes to the formatting of the equations (the vast majority.)

**Comment by bob-carpenter** [comment]
Thanks.  It's a huge help to reviewing if you can break the pull requests into bite-sized chunks. If not, it's no big deal.  I'll volunteer to review a mega-PR for any number of doc fixes.

**Comment by mitzimorris** [comment]
this looks totally awesome - happy to review your PR as is - many thanks for doing this!

**Comment by enbrown** [comment]
> this looks totally awesome - happy to review your PR as is - many thanks for doing this!

No problem. Procrastinating with typography!

Is there a Stan code highlighting style that is used by other people? Its not too difficult to add syntax highlighting (4 line change to an `_output.yml` file, annotating all Stan code blocks with `{.stan}` and including two MIT-licensed style and theme files.)

**Comment by mitzimorris** [comment]
what kind of style and theme files?  latex?  css?

**Comment by enbrown** [comment]
> what kind of style and theme files? latex? css?

Pandoc-based syntax highlighting:
https://github.com/enbrown/stan-docs/blob/format_stan_blocks/src/stan-users-guide/stan.xml
https://github.com/enbrown/stan-docs/blob/format_stan_blocks/src/stan-users-guide/stan.theme

The `_output.yml` file just needs to pass options to Pandoc to use these:
https://github.com/enbrown/stan-docs/blob/format_stan_blocks/src/stan-users-guide/_output.yml

Finally, Stan code blocks need to be identified:
````
``` {.stan}
data {
 ...
}
model {
  y ~ normal(0, 1)
}
```
````

**Comment by bob-carpenter** [comment]
I thought RMarkdown compiled Stan models when it saw them in markdown.  We don't want to try to be compiling these things as a lot of them are just program fragments.

**Comment by enbrown** [comment]
RMarkdown shows code annotated like this without actually compiling anything, but it can highlight the syntax in them: make the different program blocks one color, control flow (if/then/for) another color, known functions a different color, and distributions bold. Its purely formatting like this:

![image](https://user-images.githubusercontent.com/6978322/60533196-9fcc4c00-9cc4-11e9-952d-0c8bde178064.png)

When I annotated all Stan blocks in the user guide (375 I think), I didn't notice it take any longer to make the HTML and PDF outputs, but it could add a few seconds overall to the processing time.

**Comment by bob-carpenter** [comment]
Processing time's no big deal.  It already takes a long time to generate HTML and PDF.

Thanks much for looking into this and pasting in an example.  

I've never been crazy about this level of syntax highlighting.   I turn on the lightest mode possible in anything I'm doing as I find all the colors and fonts distracting.  I'm curious what others think on this, as I'm not the dictator of this thing.

Green and red won't work as color choices due to color blindness.   Any idea why "normal" is set in the same color as "lower"?   The block names should probably be a more distinct color, too.  

I like the lighter color for ocmments, but I'm not crazy about the italic typewriter font.  At least the font's fixed width.

**Comment by enbrown** [comment]
These were completely arbitrary choices (that I made based on the defaults which were worse) that can be modified at will. The font color and background color can be set to any RGB color. Then they can be bold or not, italicized or not, and underlined or not. These are the things that can be changed in the Pandoc theme.

It might be possible to delve deeper into the CSS and overwrite these choices (because the Stan codeblocks are actually in HTML `<code class="sourceCode stan">` elements with `<span class="XX">` subelements that do the styling. But that's likely more trouble than its worth (although you could use that to do user-customizable style selections so someone could have WILD colors and others can be monochromatic.)

**Comment by bob-carpenter** [comment]
We shouldn't hold up this PR for color choices in Stan programs.  Just please choose something relatively low contrast, with matching darknesses, and don't let users adjust it.  We can fix it later, but discussing it ad nauseum now would literally be an instance of a classic [bikeshed issue](https://en.wikipedia.org/wiki/Law_of_triviality).

Let me outline some guidelines from standard book design practice:  

* contrast shouldn't be too high so that it's easy to read
* darkness (what typographers call "color") should be matched
* keep a minimal number of fonts (ideally one)
* keep line-length down to 60 max

Together, these let you read the marked-up text like regular text much more easily and will make the text in code look more seamlessly like part of the rest of the book.   Darkness is what typographers call ["color"](https://practicaltypography.com/color.html).  It has to match for things to be readable.  And it's really the main consideration here.

In the end, we want to move to a situation where we have code in actual functional program contexts that we can check for syntax, etc., then cut into the doc.  

P.S.  CSS would be problematic as none of the components have `span` styling.

**Comment by mitzimorris** [comment]
> * [ ]  https://github.com/stan-dev/docs/blob/90cb5fd93afae84e35638da0e9f717c6cc128f03/docs/2_19/functions-reference/multivariate-normal-distribution-precision-parameterization.html#L572
> 
> https://github.com/stan-dev/docs/blob/90cb5fd93afae84e35638da0e9f717c6cc128f03/docs/2_19/functions-reference/multivariate-normal-distribution-precision-parameterization.html#L573
> 
> I think that the above section should be changed from
> `MultiNormalPrecision(y|mu, Omega) = MultiNormal(y|mu, Sigma^-1)`
> to
> `MultiNormalPrecision(y|mu, Omega) = MultiNormal(y|mu, Omega^-1)`

the documentation is correct - this statement is relating the MultiNormalPrecision to the MultiNormal - the precision parameter Omega is related to the variance parameter Sigma.

**Comment by mitzimorris** [comment]
would like to close this for 2.20 release but would also like to get @enbrown's fixes in  - where does this discussion stand?

**Comment by bertcarnell** [comment]
Sorry for missing your disagreement with my comment.  I don't think that you are correct.  Think about the mathematical statement that is being made, If K is an integer, and mu is a real vector, and Omega is a real square matrix, then for y as a real vector is distributed as multivariate normal using the Omega precision matrix, or equivalent, it is distributed as multivariate normal using the variance matrix (which is the Omega inverse).  If you introduce the Sigma matrix here, then you haven't defined it.  See the multivariate normal Cholesky parameterization as an equivalent.

**Comment by bob-carpenter** [comment]
See:  https://github.com/stan-dev/docs/issues/71

**Comment by lukas-rokka** [comment]
#### Summary:
Typo on page 106 in the Function reference documentation 2.20: 
"lognormal_rng(reals mu, reals beta)" should be "lognormal_rng(reals mu, reals sigma)"

#### Current Version:
v2.20.0

**Comment by mitzimorris** [comment]
good catch, many thanks, will fix!

**Comment by asperamanka** [comment]
In Stan function manual 2.20 chapter 15.1:
sampling statement of std_normal should be y ~ std_normal() instead of y ~ std_normal(y)

**Comment by mitzimorris** [comment]
good catch - thanks - will fix!

**Comment by wesbarnett** [comment]
Typo: "exit" -> "exist"
https://github.com/stan-dev/docs/blob/master/docs/2_21/stan-users-guide/index.html#L630

**Comment by mitzimorris** [comment]
that's funny!

**Comment by mitzimorris** [comment]
leaving this issue open until 2.22 release

note that changes suggested by enbrown have been incorporated via PRs https://github.com/stan-dev/docs/pull/90 and  https://github.com/stan-dev/docs/pull/126
