### ISSUE TITLE
Missing R-function extract_one_draw() in Introduction of bayes-stats-stan

### ISSUE THREAD

**Issue by cfbeuchel** [stan-dev/docs#4]
Hi!

I discovered the "bayes-stats-stan" documentation and started reading the Introduction on mc-stan.org ([This one](http://mc-stan.org/docs/bayes-stats-stan/introduction.html) or [the pdf-version on github](https://github.com/stan-dev/docs/blob/master/docs/bayes-stats-stan.pdf)). 

I simply wanted to reproduce the first Hello World but stumbled upon an R-function used in the example that was not provided in the document. It's not a real issue but it might be confusing/discouraging to new readers trying to reproduce the provided example. I'm referring to the function `extract_one_draw`  (Page 16 in the PDF version), or this chunk [here](http://mc-stan.org/docs/bayes-stats-stan/introduction.html):

```
y <- extract_one_draw(fake_data)$y
hello_data <- list(N=N, x=x, y=y)
```
The function `extract_one_draw` is not defined anywhere in the HTML/PDF version, but I found the chunk [here](https://github.com/stan-dev/example-models/blob/master/knitr/chapter1/chapter1.Rmd) and [here](https://github.com/stan-dev/example-models/blob/master/knitr/simplest-regression/story.Rmd) and [here](https://github.com/stan-dev/stan-book/blob/master/before-chapter.R):

```
options(htmltools.dir.version = FALSE)
options(digits = 2)
library(knitr)
knitr::opts_chunk$set(cache = TRUE)
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tufte'))
knitr::opts_chunk$set(comment = "")
print_file <- function(file) {
  cat(paste(readLines(file), "\n", sep=""), sep="")
}
extract_one_draw <- function(stanfit, chain = 1, iter = 1) {
  x <- get_inits(stanfit, iter = iter)
  x[[chain]]
}
library("arm")
library("rstan")
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
```

[This file](https://github.com/stan-dev/stan-book/blob/master/introduction.Rmd) looks like the newest version of the introduction and also does not include the function definition, which is therefore not included in the respective HTML/PDF file. I guess it was moved [here](https://github.com/stan-dev/stan-book/blob/master/before-chapter.R).

The knitr-options in all the .Rmd files are `{r setup, include=FALSE, echo=FALSE}` for the above chunk. I don't really know which exact file the PDF/HTML version on the mc-stan-website is based on but I guess this issue could be easily solved by defining the function in an `include = T, echo = T` chunk, like the one the function is called in ([maybe this one](https://github.com/stan-dev/stan-book/blob/master/introduction.Rmd#L225)). 

I hope I didn't make any mistakes or reproduced an issue or overlook anything. Thank you for creating such accessible documentation for this great software!

PS: I opened this issue before in the wrong repository (https://github.com/stan-dev/example-models) and am re-opening it here. Sorry for the mix-up

**Comment by bob-carpenter** [comment]
Thanks for filing such a carefully researched issue.  We really appreciate it.

Is the book not building from the shell scripts?

The code you're looking for defining the one-draw function is in [`src/bayes-stats-stan/before-chapter.R`](https://github.com/stan-dev/docs/blob/master/src/bayes-stats-stan/before-chapter.R).  This is how bookdown suggests code used in every chapter should be organized---as an include.  I find the bookown config very confusing in the way it is spread over  (at least) three locations, `_bookdown.yml`, `_output.yml`, and `index.Rmd`.  The specification to use `before-chapter.R` is in our `_bookdown.yml`, which contains the line

```
before_chapter_script: "before-chapter.R"
```

The reason the code in `before-chapter.R` shows up elsewhere stems from the awkward implementation of bookdown, which rather than just running `before-chapter.R`, actually pastes it into the front of each `.Rmd` file.  This means each such file is touched for each build; it tries to erase it at the end, but if you stop the build in the middle, it lingers rather than getting properly cleaned up.  Then you can get multiple before-chapter includes, so we have to keep cleaning them.  We've been fighting against this unfortunate behavior.   I filed an issue against bookdown, and they're aware of it, but they are not going to fix it as far as I know.

We're happy to entertain suggestions for how to better organize this without having to manually cut-and-paste code into the front of each chapter.  

Just as a heads up, we're going to remove *all* of the displayed R from the bookdown, because this book isn't meant to be about R, it's meant to be about Stan. The current state arose from @andrewgelman adding new material in R to the front of our user's guide (one of the new R-heavy chapters is from @jgabry's teaching material).  This needs to be cleaned up.  When there's no R at all in the text, will it be less confusing about where code is?

**Comment by cfbeuchel** [comment]
I wasn't trying to build the book but simply found it when looking for documentation and started reading. I have no experience with bookdown so I don't have any suggestions there. My simple point was, that the online HTML version on [mc-stan.org](http://mc-stan.org/docs/bayes-stats-stan/introduction.html) doesn't include the code and the `extract_one_draw`-function in `before-chapter.R` and therefore makes the example non-reproducible unless the reader cross-references the source `.Rmd` documents here on GitHub. 

R certainly makes it easier for the uninitiated user like me to get started, but the resources for that are available elsewhere (e.g. the fantastic book by Richard McElreath) and hello-world examples like this would certainly also be clear and instructive without it.

But the future goal of removing the R-code altogether renders this issue pointless, which I realize is still in the wrong repository... Thank you for taking the time to answer me. I'm looking forward to delving deeper into Stan and the book looks like a fantastic resource for this.

**Comment by bob-carpenter** [comment]
Thanks for clarifying.  I see how having some R but not all of it in the .html output is confusing.  Hopefully after I clean this up, it'll be clear that it's just pseudocode explaining what's going on at a high level.  In that way, it'll be more like the *BUGS Book* than like our case studies.

P.S.  This is the right repository.  We're going to put all the high-level doc for the language here.  The interfaces have their own documentation---RStan has a lot of nice vignettes, for example.

**Comment by gdmcdonald** [comment]
The R code seemed really useful to me, It'll be basically useless to me without it. Although I also wondered where the extract_one_draw() function was.
